# Generated by Django 4.0.3 on 2022-04-20 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='exam_types',
        ),
    ]
