# Generated by Django 4.0.3 on 2022-04-20 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_remove_subject_exam_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='exam_types',
            field=models.ManyToManyField(through='exam.SubjectToExamType', to='exam.examtype'),
        ),
    ]
