# Generated by Django 4.0.3 on 2022-04-21 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_subject_exam_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examschedule',
            name='examiners',
        ),
        migrations.DeleteModel(
            name='Examiner',
        ),
    ]
