# Generated by Django 4.0.3 on 2022-04-21 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_remove_examschedule_examiners_delete_examiner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examiner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'examiner',
            },
        ),
        migrations.AddField(
            model_name='examschedule',
            name='examiners',
            field=models.ManyToManyField(through='exam.Examiner', to='exam.tutor'),
        ),
        migrations.AddField(
            model_name='examiner',
            name='exam_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exam.examschedule'),
        ),
        migrations.AddField(
            model_name='examiner',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exam.tutor'),
        ),
    ]
