# Generated by Django 4.0.3 on 2022-04-21 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_examiner_examschedule_examiners_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='examiner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='exam.tutor'),
        ),
    ]
