# Generated by Django 4.0.3 on 2022-05-02 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_examresult_examiner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examresult',
            options={'verbose_name': 'exam result', 'verbose_name_plural': 'exam results'},
        ),
        migrations.AlterModelOptions(
            name='examschedule',
            options={'verbose_name': 'exam schedule', 'verbose_name_plural': 'exam schedule'},
        ),
        migrations.AlterModelOptions(
            name='examtype',
            options={'verbose_name': 'exam type', 'verbose_name_plural': 'exam types'},
        ),
    ]
