# Generated by Django 4.0.3 on 2022-04-04 18:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_notification_role_usertorole'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationToUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notification_to_user',
            },
        ),
        migrations.CreateModel(
            name='TargetGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'target_group',
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, through='users.NotificationToUser', to='users.user'),
        ),
        migrations.AddField(
            model_name='notificationtouser',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.notification'),
        ),
        migrations.AddField(
            model_name='notificationtouser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.user'),
        ),
        migrations.CreateModel(
            name='NotificationToTargetGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.notification')),
                ('target_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.targetgroup')),
            ],
            options={
                'db_table': 'notification_to_target_group',
                'unique_together': {('notification', 'target_group')},
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='target_groups',
            field=models.ManyToManyField(blank=True, null=True, through='users.NotificationToTargetGroup', to='users.targetgroup'),
        ),
        migrations.CreateModel(
            name='UserToTargetGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('target_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.targetgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.user')),
            ],
            options={
                'db_table': 'user_to_target_group',
                'unique_together': {('user', 'target_group')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='notificationtouser',
            unique_together={('notification', 'user')},
        ),
    ]
