# Generated by Django 4.0.3 on 2022-04-04 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_notificationtouser_targetgroup_notification_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notificationtotargetgroup',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='notificationtotargetgroup',
            name='notification',
        ),
        migrations.RemoveField(
            model_name='notificationtotargetgroup',
            name='target_group',
        ),
        migrations.AlterUniqueTogether(
            name='notificationtouser',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='notificationtouser',
            name='notification',
        ),
        migrations.RemoveField(
            model_name='notificationtouser',
            name='user',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='NotificationToTargetGroup',
        ),
        migrations.DeleteModel(
            name='NotificationToUser',
        ),
    ]
