# Generated by Django 4.0.3 on 2022-04-11 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notificationtotargetgroup',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='notificationtotargetgroup',
            name='notification',
        ),
        migrations.RemoveField(
            model_name='notificationtotargetgroup',
            name='target_group',
        ),
        migrations.AlterUniqueTogether(
            name='notificationtouser',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='notificationtouser',
            name='notification',
        ),
        migrations.RemoveField(
            model_name='notificationtouser',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='usertotargetgroup',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='usertotargetgroup',
            name='target_group',
        ),
        migrations.RemoveField(
            model_name='usertotargetgroup',
            name='user',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='NotificationToTargetGroup',
        ),
        migrations.DeleteModel(
            name='NotificationToUser',
        ),
        migrations.DeleteModel(
            name='TargetGroup',
        ),
        migrations.DeleteModel(
            name='UserToTargetGroup',
        ),
    ]
