# Generated by Django 4.0.3 on 2022-05-02 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_usertorole_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
