# Generated by Django 4.0.3 on 2022-04-12 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('role_model', '0005_permissiontouser_permission_users_and_more'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('can_read', models.BooleanField()),
                ('can_change_status', models.BooleanField()),
                ('can_edit', models.BooleanField()),
                ('is_for_all', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('document_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='documents.documenttemplate')),
            ],
            options={
                'db_table': 'document_permission',
            },
        ),
        migrations.CreateModel(
            name='DocumentToDocumentPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'document_to_document_permission',
            },
        ),
        migrations.RemoveField(
            model_name='document',
            name='permissions',
        ),
        migrations.DeleteModel(
            name='DocumentPermissionToUser',
        ),
        migrations.AddField(
            model_name='documenttodocumentpermission',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.document'),
        ),
        migrations.AddField(
            model_name='documenttodocumentpermission',
            name='document_permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.documentpermission'),
        ),
        migrations.AddField(
            model_name='documentpermission',
            name='documents',
            field=models.ManyToManyField(through='documents.DocumentToDocumentPermission', to='documents.document'),
        ),
        migrations.AddField(
            model_name='documentpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='role_model.permission'),
        ),
    ]
