# Generated by Django 4.0.3 on 2022-04-12 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_documentpermission_documenttodocumentpermission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentpermission',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
