# Generated by Django 4.0.3 on 2022-04-12 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_documentpermission_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentpermission',
            old_name='document_template',
            new_name='template',
        ),
    ]
