# Generated by Django 4.0.3 on 2022-04-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role_model', '0002_action_permission_permissiontorole_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
