# Generated by Django 4.0.3 on 2022-04-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_usertorole_unique_together_and_more'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_groups',
            field=models.ManyToManyField(blank=True, through='notifications.NotificationToNotificationGroup', to='notifications.notificationgroup'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='users',
            field=models.ManyToManyField(blank=True, through='notifications.NotificationToUser', to='users.user'),
        ),
    ]
