# Generated by Django 4.0.3 on 2022-05-08 09:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('data_sync', '0003_externalapplicationtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('body', models.TextField()),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('date', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'news',
            },
        ),
    ]
