# Generated by Django 4.0.3 on 2022-05-30 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sync', '0004_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='date',
        ),
        migrations.AddField(
            model_name='news',
            name='datetime',
            field=models.DateTimeField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='picture',
            field=models.TextField(blank=True, null=True),
        ),
    ]
